### ISSUE TITLE
ValidateKID with checksum "-" fails

### ISSUE THREAD

**Issue by hzr** [folio-as/checksum#1]
Rejected here I believe: https://github.com/folio-as/checksum/blob/b86982aa0895fa486312d97de2b66373b172e79a/kid.go#L13-L15

**Comment by karloygard** [comment]
Fixed in 990b07db3197d5aa6d47e0afccb545a5e1288f23?

**Comment by hzr** [comment]
Mod11 was fixed, but ValidateKID bails on non-numeric input I believe.

**Comment by karloygard** [comment]
You're correct. Fixing.
